"""
Tests for the CSS generated by content.js buildCSS(n).

Run with:  python3 tests/test_css.py
"""

import re
import sys
import math
import pathlib


def gap_for(n):
    """Python replica of the gap formula in buildCSS(n)."""
    return max(4, min(16, round(64 / n)))


def build_css(n):
    """Python replica of buildCSS(n) from content.js."""
    gap = gap_for(n)
    return f"""ytd-rich-grid-renderer {{
  --ytd-rich-grid-items-per-row: {n} !important;
}}
ytd-rich-grid-renderer #contents.ytd-rich-grid-renderer {{
  display: grid !important;
  grid-template-columns: repeat({n}, minmax(0, 1fr)) !important;
  gap: {gap}px !important;
}}
ytd-rich-item-renderer {{
  width: 100% !important;
  max-width: unset !important;
  min-width: 0 !important;
  margin: 0 !important;
}}
ytd-rich-grid-row #contents.ytd-rich-grid-row {{
  display: contents !important;
}}"""


def extract_block(css, selector):
    """Return the declaration block for the given selector, or empty string."""
    pattern = re.escape(selector) + r"\s*\{([^}]*)\}"
    m = re.search(pattern, css)
    return m.group(1) if m else ""


def has_property(block, prop, value_pattern=None):
    for line in block.splitlines():
        line = line.strip().rstrip(";")
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        if key.strip() == prop:
            if value_pattern is None:
                return True
            return bool(re.search(value_pattern, val.strip()))
    return False


def get_gap_value(block):
    """Return the numeric pixel value of the gap property, or None."""
    for line in block.splitlines():
        line = line.strip().rstrip(";")
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        if key.strip() == "gap":
            m = re.search(r"(\d+)px", val)
            return int(m.group(1)) if m else None
    return None


# ---------------------------------------------------------------------------
# Test helpers
# ---------------------------------------------------------------------------

passed = 0
failed = 0


def ok(condition, description):
    global passed, failed
    if condition:
        print(f"  PASS  {description}")
        passed += 1
    else:
        print(f"  FAIL  {description}")
        failed += 1


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

print("── Grid column count ──────────────────────────────────────────────")
for n in [1, 4, 6, 8, 12]:
    css = build_css(n)
    block = extract_block(css, "ytd-rich-grid-renderer #contents.ytd-rich-grid-renderer")
    ok(
        has_property(block, "grid-template-columns", rf"repeat\({n},"),
        f"n={n}: grid-template-columns uses repeat({n}, ...)",
    )
    ok(
        has_property(block, "display", "grid"),
        f"n={n}: display is grid",
    )

print()
print("── Gap is present and uses !important ─────────────────────────────")
for n in [1, 6, 12]:
    css = build_css(n)
    block = extract_block(css, "ytd-rich-grid-renderer #contents.ytd-rich-grid-renderer")
    ok(has_property(block, "gap"), f"n={n}: gap property is set")
    ok(has_property(block, "gap", r"!important"), f"n={n}: gap uses !important")
    ok(has_property(block, "gap", r"\d+px"), f"n={n}: gap is a pixel value")

print()
print("── Gap scales down as columns increase ────────────────────────────")
prev_gap = None
for n in [1, 2, 4, 6, 8, 12]:
    gap = gap_for(n)
    ok(4 <= gap <= 16, f"n={n}: gap={gap}px is within 4–16px range")
    if prev_gap is not None:
        ok(gap <= prev_gap, f"n={n}: gap={gap}px ≤ previous gap={prev_gap}px (decreasing)")
    prev_gap = gap

# Spot-check expected values
ok(gap_for(4) == 16, "n=4: gap is 16px")
ok(gap_for(6) == 11, "n=6: gap is 11px")
ok(gap_for(8) == 8,  "n=8: gap is 8px")
ok(gap_for(12) == 5, "n=12: gap is 5px")

print()
print("── Gap in generated CSS matches formula ───────────────────────────")
for n in [1, 4, 6, 8, 12]:
    css = build_css(n)
    block = extract_block(css, "ytd-rich-grid-renderer #contents.ytd-rich-grid-renderer")
    actual = get_gap_value(block)
    expected = gap_for(n)
    ok(actual == expected, f"n={n}: CSS gap={actual}px matches formula gap={expected}px")

print()
print("── Item margins reset ─────────────────────────────────────────────")
for n in [1, 6, 12]:
    css = build_css(n)
    block = extract_block(css, "ytd-rich-item-renderer")
    ok(has_property(block, "margin", r"^0\s"), f"n={n}: ytd-rich-item-renderer margin is 0")
    ok(has_property(block, "width", r"100%"),  f"n={n}: ytd-rich-item-renderer width is 100%")

print()
print("── Row display:contents ───────────────────────────────────────────")
css = build_css(6)
block = extract_block(css, r"ytd-rich-grid-row #contents.ytd-rich-grid-row")
ok(has_property(block, "display", "contents"), "ytd-rich-grid-row #contents has display: contents")

print()
print("── CSS variable set on renderer ───────────────────────────────────")
css = build_css(6)
block = extract_block(css, "ytd-rich-grid-renderer")
ok(
    has_property(block, "--ytd-rich-grid-items-per-row", "6"),
    "ytd-rich-grid-renderer sets --ytd-rich-grid-items-per-row to column count",
)

# ---------------------------------------------------------------------------
# Sync check: compare build_css() against content.js buildCSS template
# ---------------------------------------------------------------------------
print()
print("── Sync check: content.js matches test replica ────────────────────")

js_source = pathlib.Path(__file__).parent.parent / "content.js"
js_text = js_source.read_text()

# Extract the template literal from buildCSS (after the gap const)
m = re.search(r"function buildCSS\(n\)\s*\{.*?return\s*`(.*?)`\.trim\(\)", js_text, re.DOTALL)
if m:
    js_template = m.group(1).strip()
    # Simulate JS: gap = max(4, min(16, round(64/6))) = 11
    gap_6 = gap_for(6)
    js_rendered = js_template.replace("${n}", "6").replace("${gap}", str(gap_6))
    py_rendered = build_css(6).strip()
    ok(js_rendered == py_rendered, "build_css() in test matches buildCSS() in content.js")
    if js_rendered != py_rendered:
        print("    Expected (content.js):")
        for line in js_rendered.splitlines():
            print(f"      {line}")
        print("    Got (test replica):")
        for line in py_rendered.splitlines():
            print(f"      {line}")
else:
    ok(False, "Could not parse buildCSS() from content.js")

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
print()
print(f"{'─' * 60}")
print(f"  {passed} passed, {failed} failed")
sys.exit(0 if failed == 0 else 1)
